import type {
  MediaCatalogCard,
  MediaDetail,
  MediaResources,
} from './mediaReleaseProtocol';
import type {
  MovieFeedItem,
  MovieResource,
} from './resourceFeedProtocol';

export function mediaFeedItemFromCatalogCard(
  card: MediaCatalogCard,
  rank: number,
  endpoint: string,
  releaseId: string,
): MovieFeedItem {
  return {
    rank,
    movie_id: card.media_id,
    source_id: 'media-release',
    source_item_key: card.media_id,
    detail_url: `${endpoint}${card.detail_object.path}`,
    listing_title: card.title,
    content_kind: card.content_kind,
    series_title: card.content_kind === 'series' ? card.title : null,
    season_number: card.season_number ?? null,
    episode_number: card.episode_number ?? null,
    episode_label: card.episode_label ?? null,
    update_status: card.update_status ?? null,
    title: card.title,
    original_title: card.original_title ?? null,
    year: card.year ?? null,
    update_date: card.update_date ?? null,
    release_date: null,
    duration_minutes: null,
    countries: card.countries,
    genres: card.genres,
    languages: [],
    directors: [],
    actors: [],
    imdb_id: null,
    imdb_rating: card.imdb_rating ?? null,
    imdb_rating_text: card.imdb_rating === null || card.imdb_rating === undefined ? null : String(card.imdb_rating),
    douban_rating: card.douban_rating ?? null,
    douban_rating_text: card.douban_rating === null || card.douban_rating === undefined ? null : String(card.douban_rating),
    douban_url: null,
    rotten_tomatoes_rating: card.rotten_tomatoes_rating ?? null,
    rotten_tomatoes_rating_text: card.rotten_tomatoes_rating === null || card.rotten_tomatoes_rating === undefined
      ? null
      : `${card.rotten_tomatoes_rating}%`,
    rotten_tomatoes_url: null,
    bangumi_rating: card.bangumi_rating ?? null,
    bangumi_rating_text: card.bangumi_rating === null || card.bangumi_rating === undefined ? null : String(card.bangumi_rating),
    bangumi_subject_id: null,
    bangumi_url: null,
    cover_source_url: null,
    cover_asset_path: null,
    cover_width: null,
    cover_height: null,
    synopsis: null,
    recommended: card.recommended,
    highlight_labels: card.highlight_labels,
    quality_tags: card.quality_tags,
    resources: [],
    resource_count_hint: card.resource_count,
    remote_cover_url: `${endpoint}${card.cover.path}`,
    remote_endpoint: endpoint,
    remote_release_id: releaseId,
    remote_detail_path: card.detail_object.path,
    remote_detail_hash: card.detail_object.hash,
    remote_detail_size: card.detail_object.size,
  };
}

export function mergeMediaDetailIntoFeedItem(
  item: MovieFeedItem,
  detail: MediaDetail,
  resources: MediaResources,
  endpoint: string,
): MovieFeedItem {
  const mappedResources: MovieResource[] = resources.items.map((resource) => ({
    resource_type: resource.resource_type,
    provider: resource.provider,
    url: resource.url,
    info_hash: resource.info_hash ?? null,
    display_title: resource.display_title,
    extraction_code: resource.extraction_code ?? null,
    quality_tags: resource.quality_tags,
  }));
  return {
    ...item,
    detail_url: `${endpoint}${item.remote_detail_path ?? ''}`,
    title: detail.title,
    original_title: detail.original_title ?? null,
    year: detail.year ?? null,
    release_date: detail.release_date ?? null,
    duration_minutes: detail.duration_minutes ?? null,
    countries: detail.countries,
    genres: detail.genres,
    languages: detail.languages,
    directors: detail.directors,
    actors: detail.actors,
    imdb_id: detail.imdb_id ?? null,
    imdb_rating: detail.imdb_rating ?? item.imdb_rating,
    imdb_rating_text: detail.imdb_rating_text ?? item.imdb_rating_text,
    douban_rating: detail.douban_rating ?? item.douban_rating,
    douban_rating_text: detail.douban_rating_text ?? item.douban_rating_text,
    douban_url: detail.douban_url ?? item.douban_url,
    rotten_tomatoes_rating: detail.rotten_tomatoes_rating ?? item.rotten_tomatoes_rating,
    rotten_tomatoes_rating_text: detail.rotten_tomatoes_rating_text ?? item.rotten_tomatoes_rating_text,
    rotten_tomatoes_url: detail.rotten_tomatoes_url ?? item.rotten_tomatoes_url,
    bangumi_rating: detail.bangumi_rating ?? item.bangumi_rating,
    bangumi_rating_text: detail.bangumi_rating_text ?? item.bangumi_rating_text,
    bangumi_subject_id: detail.bangumi_subject_id ?? item.bangumi_subject_id,
    bangumi_url: detail.bangumi_url ?? item.bangumi_url,
    synopsis: detail.synopsis ?? null,
    resources: mappedResources,
    resource_count_hint: mappedResources.length,
    remote_endpoint: endpoint,
  };
}
